# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c137c60e3ec96c8f7dc2f6994166f740da060343e52cdbbef1c8119b4aab2dc5c6aeb519d0a0c12385b348ee9df52d20b8a3b4e5e0d1e580cbf101a14c8a0a76

test:
  secret_key_base: 300baca4c070336649ed8258037a91a30b3c9b0d49b830a18dd255e3f782c6daec47f8e55e776849c2c3b68525ca5d2898026009864085910787102e64a2ef1b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
